name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
      - "improvement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
exclude-labels:
  - "skip-changelog"
template: |
  ## What’s Changed
  $CHANGES
