#!/usr/bin/with-contenv bash

CUSER="${CUSTOM_USER:-chromium}"

# default file copies first run
if [[ ! -f /home/${CUSER}/.config/openbox/autostart ]]; then
  mkdir -p /home/${CUSER}/.config/openbox
  cp /defaults/autostart /home/${CUSER}/.config/openbox/autostart
  chown -R ${CUSER}:${CUSER} /home/${CUSER}/.config/openbox
fi
if [[ ! -f /home/${CUSER}/.config/openbox/menu.xml ]]; then
  mkdir -p /home/${CUSER}/.config/openbox && \
  cp /defaults/menu.xml /home/${CUSER}/.config/openbox/menu.xml && \
  chown -R ${CUSER}:${CUSER} /home/${CUSER}/.config
fi
if [[ -f /usr/local/etc/kasmvnc/kasmvnc.yaml.lsio ]]; then
  mv \
    /usr/local/etc/kasmvnc/kasmvnc.yaml.lsio \
    /usr/local/etc/kasmvnc/kasmvnc.yaml
fi

# XDG Home
printf "${HOME}/.XDG" > /run/s6/container_environment/XDG_RUNTIME_DIR
if [ ! -d "${HOME}/.XDG" ]; then
  mkdir -p ${HOME}/.XDG
  chown ${CUSER}:${CUSER} ${HOME}/.XDG
fi
