#!/usr/bin/with-contenv bash

CUSER="${CUSTOM_USER:-chromium}"
CUSER_UID="${CUSTOM_USER_UID:-12345}"
CUSER_GID="${CUSTOM_USER_G:-12345}"

addgroup --gid ${CUSER_GID} ${CUSER}
adduser -D --uid ${CUSER_UID} -h /home/${CUSER} -G ${CUSER} ${CUSER}