name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup env
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push amd64
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.amd64
          tags: zerogate/zerogate-browser:latest,zerogate/zerogate-browser:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
            ENVIRONMENT=production
          context: .
          platforms: linux/amd64
      - name: Build and push arm64
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile
          tags: zerogate/zerogate-browser:arm64v8-latest,zerogate/zerogate-browser:arm64v8-${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
            ENVIRONMENT=production
          context: .
          platforms: linux/arm64
